### ISSUE TITLE
missing lang strings

### ISSUE THREAD

**Issue by jmvedrine** [jayeshanandani/moodle-mod_qpractice#2]
Hello Jayesh,
How are you ? Academic years has started for me, and I met my new students 3 days ago.
I noticed yesterday that there are missing strings for capabilities:
$string['qpractice:addinstance'] = 'Add a qpractice instance';
$string['qpractice:attempt'] = 'Attempt a qpractice session';
$string['qpractice:view'] = 'View a qpractice session';
$string['qpractice:viewallreports'] = 'View all qpractice reports';
$string['qpractice:viewmyreport'] = 'View my qpractice report';

**Comment by jayeshanandani** [comment]
Hi Jean-Michel,
  I am doing good.Had a good break in between. Good to see you are back to teaching. I have added those strings and right now I am working ddorder.

I have pushed the changes upstream and now code looks better.
